# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.9.2 on 2016-04-06 15:46
from __future__ import unicode_literals

from django.db import migrations


def remove_memberships_of_cancelled_users_acounts(apps, schema_editor):
    Membership = apps.get_model("projects", "Membership")
    Membership.objects.filter(user__is_active=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20160322_1157'),
    ]

    operations = [
        migrations.RunPython(remove_memberships_of_cancelled_users_acounts),
    ]
