# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20160530_1004'),
        ('projects', '0042_auto_20160525_0911'),
    ]

    operations = [
    ]
