# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20160531_1150'),
        ('projects', '0042_auto_20160525_0911'),
    ]

    operations = [
    ]
