# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.9.2 on 2016-07-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20160629_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='epics_csv_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, editable=False, max_length=32, null=True),
        ),
    ]
