# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20161215_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='looking_for_people_note',
            field=models.TextField(blank=True, default='', verbose_name='looking for people note'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='looking_for_people_note',
            field=models.TextField(blank=True, default='', verbose_name='looking for people note'),
        ),
    ]
