# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20170116_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('by_default', models.BooleanField(default=False, verbose_name='by default')),
                ('color', models.CharField(default='#999999', max_length=20, verbose_name='color')),
                ('days_to_due', models.IntegerField(blank=True, default=None, null=True, verbose_name='days to due')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_duedates', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'user story due date',
                'verbose_name_plural': 'user story due dates',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='default_us_duedate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.UserStoryDueDate', verbose_name='default US duedate'),
        ),
        migrations.AlterUniqueTogether(
            name='userstoryduedate',
            unique_together=set([('project', 'slug'), ('project', 'name')]),
        ),
    ]
