# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.11.2 on 2018-09-18 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20180614_1338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuestatus',
            unique_together=set([('project', 'name'), ('project', 'slug')]),
        ),
    ]
