# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20180605_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('by_default', models.BooleanField(default=False, verbose_name='by default')),
                ('color', models.CharField(default='#999999', max_length=20, verbose_name='color')),
                ('days_to_due', models.IntegerField(blank=True, default=None, null=True, verbose_name='days to due')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_duedates', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'issue due date',
                'verbose_name_plural': 'issue due dates',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('by_default', models.BooleanField(default=False, verbose_name='by default')),
                ('color', models.CharField(default='#999999', max_length=20, verbose_name='color')),
                ('days_to_due', models.IntegerField(blank=True, default=None, null=True, verbose_name='days to due')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_duedates', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'task due date',
                'verbose_name_plural': 'task due dates',
                'ordering': ['project', 'order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='taskduedate',
            unique_together=set([('project', 'name'), ('project', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='issueduedate',
            unique_together=set([('project', 'name'), ('project', 'slug')]),
        ),
    ]
