# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 11:01
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20180606_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_issue_duedate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.IssueDueDate', verbose_name='default issue duedate'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_task_duedate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.TaskDueDate', verbose_name='default task duedate'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='us_duedates',
            field=taiga.base.db.models.fields.json.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='us statuses'),
        ),
    ]
