# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 11:11
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20180606_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='issue_duedates',
            field=taiga.base.db.models.fields.json.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='issue duedates'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='task_duedates',
            field=taiga.base.db.models.fields.json.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='task duedates'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='us_duedates',
            field=taiga.base.db.models.fields.json.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='us duedates'),
        ),
    ]
