# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20180606_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_issue_duedate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_task_duedate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_us_duedate',
        ),
    ]
