# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 2.2.15 on 2020-10-07 16:04

from django.db import migrations, models
import django.db.models.deletion
import taiga.base.utils.time


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20200615_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('order', models.BigIntegerField(default=taiga.base.utils.time.timestamp_ms, verbose_name='order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlanes', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'swimlane',
                'verbose_name_plural': 'swimlanes',
                'ordering': ['project', 'order', 'name'],
            },
        ),
    ]
