# Generated by Django 2.2.14 on 2020-11-23 16:52

from django.db import migrations, models
import django.db.models.deletion


def set_first_swimlane_as_default(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    projects =  Project.objects.annotate(count=models.Count('swimlanes')).filter(count__gt=0)
    for project in projects:
        project.default_swimlane = project.swimlanes.order_by('order').first()
        project.save()


def empty_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_swimlaneuserstorystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_swimlane',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Swimlane', verbose_name='default swimlane'),
        ),
        migrations.RunPython(set_first_swimlane_as_default, empty_reverse),
    ]
