# Generated by Django 2.2.17 on 2020-12-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_project_default_swimlane'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swimlane',
            unique_together={('project', 'name')},
        ),
    ]
