# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 2.2.17 on 2020-12-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_project_default_swimlane'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swimlane',
            unique_together={('project', 'name')},
        ),
    ]
