# Generated by Django 3.2.25 on 2025-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived_code',
            field=models.CharField(blank=True, choices=[('archived-by-staff', 'Archived by staff')], default=None, max_length=255, null=True, verbose_name='Archived code'),
        ),
    ]
