# Generated by Django 2.2.19 on 2021-05-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_backlog_order_kanban',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Default backlog ordering for new stories in kanban workflow'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_backlog_order_scrum',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Default backlog ordering for new stories in scrum workflow'),
        ),
    ]
