# Generated by Django 3.2.25 on 2026-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_project_archived_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicstatus',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='is archived'),
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='is archived'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='is archived'),
        ),
    ]
