# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0002_epic_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relateduserstory',
            unique_together=set([('user_story', 'epic')]),
        ),
    ]
