# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.10.3 on 2016-12-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20160928_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, verbose_name='slug'),
        ),
    ]
