# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='key',
        ),
    ]
