# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160208_1751'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE users_role SET permissions = ARRAY_REMOVE(permissions, 'vote_issues')"
        ),
    ]
