# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.10.6 on 2017-04-06 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_json_to_jsonb'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX ON users_user (UPPER('username'))"),
        migrations.RunSQL("CREATE INDEX ON users_user (UPPER('email'))"),
    ]
