# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180514_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='read_new_terms',
            field=models.BooleanField(default=False, verbose_name='new terms read'),
        ),
    ]
