# Generated by Django 2.2.12 on 2020-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180610_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='colorize_tags',
            field=models.BooleanField(blank=True, default=False, verbose_name='colorize tags'),
        ),
    ]
