# Generated by Django 2.2.19 on 2021-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210108_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date cancelled'),
        ),
    ]
