# Generated by Django 2.2.24 on 2021-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_date_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_memberships_private_projects',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='max number of memberships of different users for all owned private project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_memberships_public_projects',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='max number of memberships of different users for all owned public project'),
        ),
    ]
