# Generated by Django 3.2.25 on 2026-09-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20211110_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
