# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 12:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0011_userstory_tribe_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='external_reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=False, null=False), blank=True, default=None, null=True, size=None, verbose_name='external reference'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None, verbose_name='tags'),
        ),
    ]
