# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userstories', '0015_add_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_userstories', to=settings.AUTH_USER_MODEL, verbose_name='assigned users'),
        ),
    ]
