# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 2.2.12 on 2020-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0018_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='from_task_ref',
            field=models.TextField(blank=True, null=True, verbose_name='reference from task'),
        ),
    ]
