# Generated by Django 3.2.19 on 2025-06-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0067_auto_20201230_1237'),
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='requestors',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to give feedback', related_name='requested_userstories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserStoryFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('good', 'Good'), ('excellent', 'Excellent'), ('amazing', 'Amazing')], max_length=10)),
                ('feedback_text', models.TextField(verbose_name='feedback text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstory_feedbacks', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstory_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='userstories.userstory')),
            ],
            options={
                'verbose_name': 'user story feedback',
                'verbose_name_plural': 'user story feedbacks',
                'unique_together': {('user_story', 'user')},
            },
        ),
    ]
