# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.9.2 on 2016-06-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20160629_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='project',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
