# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.9.2 on 2016-10-11 12:17
from __future__ import unicode_literals

from django.db import migrations
import taiga.base.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20160629_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='values_diff_cache',
            field=taiga.base.db.models.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
