# Generated by Django 2.2.12 on 2020-06-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_add_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, verbose_name='is blocked'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_iocaine',
            field=models.BooleanField(blank=True, default=False, verbose_name='is iocaine'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='userstories.UserStory', verbose_name='user story'),
        ),
    ]
