# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 1.10.4 on 2017-01-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_auto_20160617_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='from_comment',
            field=models.BooleanField(default=False, verbose_name='from_comment'),
        ),
    ]
